sonar.projectKey=dandelion
sonar.projectName=dandelion
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.stryker-tmp/**,**/ts-coverage/**,qa/**,perf/**
sonar.javascript.lcov.reportPaths=.marestail/ts-coverage/lcov.info
sonar.sourceEncoding=UTF-8
